

-- function myCallback(msg)
--    lea.log(msg)
-- end
--
-- function lea.onConfigure()
--    lea.log("onConfig")
-- end
--
-- function lea.onInit()
--    lea.log("onInit")
--
--    icon = lea.icon.load("cactus.svg")
--    tray = lea.tray.create(icon)
--    lea.tray.setMousePressHandler(tray, myCallback, "user data")
--
--    lea.log("done")
-- end
--
-- function lea.onQuit()
--    lea.log("onQuit")
-- end
